services:
  - type: web
    name: jdapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: 
      - key: COHERE_API_KEY
        value: 
      - key: UNSPLASH_ACCESS_KEY
        value: 
    plan: free